{
 "title": "Alerting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Servers availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "Storage usage percent",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,exported_namespace) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"prometheus-server\"} )) / (max by (persistentvolumeclaim,exported_namespace) (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"prometheus-server\"})) * 100"
    }
   ]
  },
  {
   "title": "Nodes K8s availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",namespace=\"prometheus\"}) by (node)",
     "legendFormat": "{{exported_node}}"
    }
   ]
  },
  {
   "title": "Memory Pressure errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\",namespace=\"prometheus\"}) by (node)",
     "legendFormat": "{{exported_node}}"
    }
   ]
  },
  {
   "title": "Disk Pressure errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\",namespace=\"prometheus\"}) by (node)",
     "legendFormat": "{{exported_node}}"
    }
   ]
  },
  {
   "title": "Network availability errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\",status=\"true\",namespace=\"prometheus\"}) by (node)",
     "legendFormat": "{{exported_node}}"
    }
   ]
  },
  {
   "title": "PIDPressure errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\",namespace=\"prometheus\"}) by (node)",
     "legendFormat": "{{exported_node}}"
    }
   ]
  }
 ]
}