{
 "title": "Kubernetes Pods (Prometheus)",
 "description": "A dashboard to view pod metrics by namespace and pod names.\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster. It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "pod_name" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}[5m]) ) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Top conso CPU",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}[5m]) / $__interval_ms * 1000) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Top conso mémoire",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}[5m])/$__interval_ms*1000) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container!=\"\", pod=~\"[[pod_name]].*\", namespace=\"[[namespace]]\"}[5m])/$__interval_ms*1000) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}